language: csharp
mono: none
solution: zbw.car.rent.api.sln
dotnet: 2.1.4
dist: trusty
sudo: required
script:
- cd ./zbw.car.rent.api
- dotnet restore
- dotnet build
deploy:
  provider: azure_web_apps
  verbose: true
